### ISSUE TITLE
`len(adjacentTiles) > 0` in World.py

### ISSUE THREAD

**Issue by hexaron** [JanOuborny/DorfromantikSimulation#1]
What does this line do:

https://github.com/JanOuborny/DorfromantikSimulation/blob/817ce8d680daffb72a87857d57398049b0134e05/World.py#L31

Since the documentation for `getAdjacentTilesAt()` states

> [...]
> Empty positions are filled with None.

the length should always be `6` right?

**Comment by JanOuborny** [comment]
Fixed in 5679725d39644d246f9d49c2813f5f9ffe8dd7d6
